---
- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    groups: sudo
    append: yes
  check_mode: no 

- name: Add SSH key for ansible user
  ansible.builtin.authorized_key:
    user: ansible
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIClODRC6obJ/90bm5w5ooqv0TnomIXj19KVG/Nnta0yz security-lab"
   
- name: Allow ansible user to use sudo without password
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
